;;; This file is autogenerated by repl.components/create-component!
;;; Do not modify manually
(clojure.core/ns components.core (:require [components.todo-list.core] [components.root.core]))
(do (def todo-list components.todo-list.core/todo-list) (def root components.root.core/root))